#!/bin/bash

. /home/kdata.conf

if [ -f /etc/kdata/Renew.SSL.Letencrypt ] && [ -f /etc/cron.d/kdata.autorenew.ssl.cron ]; then
clear
echo "========================================================================="
echo "Chuc nang tu dong gia han chung chi SSL Let's Encrypt da duoc BAT."
echo "-------------------------------------------------------------------------"
echo "KPANEL se auto renew SSL vao luc 00:00 ngay 1 hang thang."
/etc/kdata/menu/ssl_free/kdata-letsencrypt-menu
fi
echo "========================================================================="
echo "Su dung chuc nang nay BAT chuc nang tu dong gia han chung chi SSL cho"
echo "-------------------------------------------------------------------------"
echo "tat ca website dang su dung SSL Let's Encrypt."
echo "========================================================================="
  read -r -p "Ban muon BAT chuc nang tu dong gia han SSL ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ..."; sleep 3

cat > "/etc/kdata/Renew.SSL.Letencrypt" <<END
#!/bin/sh
/root/.acme.sh/acme.sh --renewAll
END
chmod +x /etc/kdata/Renew.SSL.Letencrypt
echo "SHELL=/bin/sh" > /etc/cron.d/kdata.autorenew.ssl.cron
echo "0 0 1 * * root /etc/kdata/Renew.SSL.Letencrypt >/dev/null 2>&1" >> /etc/cron.d/kdata.autorenew.ssl.cron
service crond restart
clear
echo "========================================================================="
echo "Hoan thanh cai dat tu dong gia han chung chi SSL Let's Encrypt."
echo "-------------------------------------------------------------------------"
echo "KPANEL se auto renew SSL vao luc 00:00 ngay 1 hang thang."
/etc/kdata/menu/ssl_free/kdata-letsencrypt-menu
;;
    *)
clear 
echo "========================================================================= "
echo "Cancel !"
/etc/kdata/menu/ssl_free/kdata-letsencrypt-menu
        ;;
esac
