#!/bin/bash
prompt="Lua chon cua ban:"
options=( "Restart MySQL" "Restart Nginx" "Restart PHP-FPM" "Restart VPS" "Exit" )
printf "=========================================================================\n"
printf "                KPANEL - Manage VPS/Server by KDATA.VN \n"
printf "=========================================================================\n"
printf "                            Restart Service\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


    1) /etc/kdata/menu/tienich/kdata-restart-mysql;;
    2) /etc/kdata/menu/tienich/kdata-restart-nginx;;
    3) /etc/kdata/menu/tienich/kdata-restart-php;;
    4) /etc/kdata/menu/tienich/kdata-reboot-vps;;
    5) clear && /etc/kdata/menu/kdata-tien-ich;;

            *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac
done
