#!/bin/bash

# https://packagecloud.io/varnishcache/
# https://packagecloud.io/varnishcache/varnish62/install#bash-rpm

/etc/kdata/menu/varnish/install-varnish-begin
echo "6.2" >> /etc/kdata/varnish.version

curl -s https://packagecloud.io/install/repositories/varnishcache/varnish62/script.rpm.sh | sudo bash

/etc/kdata/menu/varnish/install-varnish-end
