#!/bin/sh

echo "Install git..."
sudo yum -y install git > /dev/null 2>&1

# update code
if [ -d /opt/vps_kdata ]; then
cd ~ ; cd /opt/vps_kdata && git pull origin master ; cd ~
#git pull origin master
#git pull origin
fi

cd ~

sleep 5

find /opt/vps_kdata/scripts/kdata/menu -type f -exec chmod 755 {} \;
/opt/vps_kdata/scripts/kdata/menu/git-clone-done
