#!/bin/bash
. /home/kdata.conf
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 1
rm -rf /tmp/*kdata*
mkdir -p /tmp/sitedangdenyrunscriptkdata
ls /etc/nginx/conf.d > /tmp/kdata-websitelist
sed -i 's/\.conf//g' /tmp/kdata-websitelist 
sowebsitetrenserver=$(cat /tmp/kdata-websitelist | wc -l)
sowebsite=$(cat /tmp/kdata-websitelist)
for website in $sowebsite 
do
if [ -f /etc/nginx/conf.d/$website.conf ]; then
if [ "$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/$website.conf)" == "include /etc/nginx/conf/deny-script-writeable-folder.conf;" ]; then
touch /tmp/sitedangdenyrunscriptkdata/$website
fi
fi
if [ -f /etc/nginx/conf.d/www.$website.conf ]; then
if [ "$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/www.$website.conf)" == "include /etc/nginx/conf/deny-script-writeable-folder.conf;" ]; then
touch /tmp/sitedangdenyrunscriptkdata/www.$website
fi
fi
done
clear
echo "========================================================================="
echo "Website tren server: $sowebsitetrenserver"
echo "-------------------------------------------------------------------------"
if [ "$(ls -1 /tmp/sitedangdenyrunscriptkdata | wc -l)" == "0" ]; then
echo "Website KHONG CHO PHEP chay script trong writeable folder: 0"
else
echo "Website KHONG CHO PHEP chay script trong writeable folder: $(ls -1 /tmp/sitedangdenyrunscriptkdata | wc -l)"
echo "-------------------------------------------------------------------------"
ls /tmp/sitedangdenyrunscriptkdata | pr -3 -t
rm -rf /tmp/*kdata*
fi
/etc/kdata/menu/kdata-tien-ich
