#!/bin/sh
. /home/kdata.conf
if [ "$(grep KDATA.VN /bin/kdata)" != "" ]; then
clear
echo "========================================================================= "
echo "You are using Vietnamese Version"
echo "-------------------------------------------------------------------------"
echo "( Ban dang su dung ngon ngu Tieng Viet )"
/etc/kdata/menu/kdata-thay-doi-ngon-ngu-menu
exit
fi

echo "========================================================================= "
echo "Su dung chuc nang nay de thay doi ngon ngu KDATA sang tieng Viet"
echo "-------------------------------------------------------------------------"
echo "KDATA ho tro Tieng Anh & Tieng Viet"
echo "========================================================================= "
read -r -p "Ban muon thay doi ngon ngu KDATA sang Tieng Viet ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ... "
sleep 1
echo "-------------------------------------------------------------------------"
wget -q --no-check-certificate https://kdata.vn/script/kdata/motd -O /etc/motd
wget -q --no-check-certificate https://kdata.vn/script/kdata/kdata -O /bin/kdata && chmod +x /bin/kdata
cd /etc/kdata/
rm -rf /etc/kdata/menu.zip
wget -q --no-check-certificate https://kdata.vn/script/kdata/menu.zip

#Check menu.zip files

rm -rf /tmp/menu
unzip -q -o menu.zip -d /tmp
if [ ! -f /tmp/menu/kdata-tien-ich ]; then
rm -rf /tmp/menu
clear
echo "========================================================================="
echo "There's an error in changing language process"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/kdata/menu/kdata-update-upgrade-service-menu
exit
fi
## Finish check menu.zip
rm -rf /tmp/menu
unzip -q -o menu.zip
rm -rf /etc/kdata/menu.zip
cd
wget -q --no-check-certificate https://kdata.vn/script/kdata/motd -O /etc/motd
download_main_menu () {
wget -q --no-check-certificate https://kdata.vn/script/kdata/kdata -O /bin/kdata && chmod +x /bin/kdata
}
download_main_menu
checkkdata_mainmenu=`cat /bin/kdata`
if [ -z "$checkkdata_mainmenu" ]; then
download_main_menu
fi
find /etc/kdata/menu -type f -exec chmod 755 {} \;
clear 
echo "========================================================================= "
echo "Change Language of KDATA to Vietnamese Finished"
echo "-------------------------------------------------------------------------"
echo "( Thay doi ngon ngu KDATA sang tieng Viet thanh cong )"
/etc/kdata/menu/kdata-thay-doi-ngon-ngu-menu
       ;;
    *)
        echo ""
        ;;
esac
clear
clear
echo "========================================================================="
echo "Cancel Change Language for KDATA"
echo "-------------------------------------------------------------------------"
echo "Huy bo thay doi ngon ngu cho KDATA"
/etc/kdata/menu/kdata-thay-doi-ngon-ngu-menu
