#!/bin/sh
. /home/kdata.conf
if [ ! -f /etc/kdata/uploadsite ]; then
clear
echo "========================================================================="
echo "Ban chua cai dat File Manager cho Server !"
/etc/kdata/menu/kdata-web-upload-menu
exit
fi
echo "Please wait..."; sleep 1
uploadsite=$(cat /etc/kdata/uploadsite)
clear
echo "========================================================================="
echo "Domain cai dat File Manager cho Server: "
echo "-------------------------------------------------------------------------"
echo "http://$uploadsite "
/etc/kdata/menu/kdata-web-upload-menu
