#!/bin/bash
. /home/kdata.conf

cd ~

if [ ! -d /etc/kdata/.tmp ]; then
mkdir -p /etc/kdata/.tmp
fi


#checkketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://kdata.vn/script/kdata/kdata.newversion" )
checkketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://raw.githubusercontent.com/kdatavn/kdata-vps/master/version" )
#echo $checkketnoi
if [[ "$checkketnoi" == "000" ]]; then
clear
echo "========================================================================="
echo "Co loi xay ra trong qua trinh update"
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai !"
kdata
exit
fi

#
install_yum_cron_update(){
yum -y remove yum-updatesd
yum -y install yum-cron

current_os_version=$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))
if [ "$current_os_version" == "6" ]; then
service yum-cron start
chkconfig yum-cron on
else
sudo systemctl enable yum-cron
sudo systemctl start yum-cron
systemctl restart yum-cron
fi
#cd /etc/yum
cat /var/log/cron | grep yum-daily
cat /var/log/yum.log | grep Updated
}

#
rm -rf /etc/kdata/.tmp/kdata-update-*

# update glibc
### Check GLIBC 2.17 tren centos6 - Fix loi VPSKDATA tu phien ban 4.2.0.8 tro ve cai dat san tren server
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
wget --no-check-certificate -q https://raw.githubusercontent.com/kdatavn/kdata-vps/master/scripts/kdata/kdata-update-glibc -O /etc/kdata/.tmp/kdata-update-glibc
chmod +x /etc/kdata/.tmp/kdata-update-glibc
bash /etc/kdata/.tmp/kdata-update-glibc
fi


## Bat dau thuc hien update VPSKDATA
#wget -q https://kdata.vn/script/kdata/kdata-update-run -O /etc/kdata/.tmp/kdata-update-run && chmod +x /etc/kdata/.tmp/kdata-update-run
wget --no-check-certificate -q https://raw.githubusercontent.com/kdatavn/kdata-vps/master/scripts/kdata/kdata-update-run -O /etc/kdata/.tmp/kdata-update-run
chmod +x /etc/kdata/.tmp/kdata-update-run
bash /etc/kdata/.tmp/kdata-update-run


