#!/bin/bash 

. /home/kdata.conf
if [ -f /etc/csf/csf.conf ]; then
echo "Please wait....";sleep 1
csf -x
clear
echo "========================================================================= "
echo "Da tat thanh cong CSF Firewall. ! "
/etc/kdata/menu/CSF-Fiwall/kdata-csf-firewall-menu
else
echo "========================================================================= "
echo "Chuc nang nay can CSF Firewall de hoat dong"
echo "-------------------------------------------------------------------------"
echo "CSF Firewall chua cai dat tren server "
echo "-------------------------------------------------------------------------"
read -r -p "Ban co muon cai dat CSF Firewall ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
/etc/kdata/menu/CSF-Fiwall/kdata-cai-dat-csf-csf
clear
echo "========================================================================= "
echo "Cai dat va config thanh cong CSF Firewall"
/etc/kdata/menu/CSF-Fiwall/kdata-csf-firewall-menu
;;
esac
clear
echo "========================================================================= "
echo "Ban huy bo cai dat CSF Firewall ! "
/etc/kdata/menu/CSF-Fiwall/kdata-csf-firewall-menu
exit
fi
