#!/bin/bash
. /home/kdata.conf
. /etc/sysconfig/memcached
prompt="Nhap lua chon cua ban:"
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
options=("Disable Memcached" "Restart Memcached" "Config Memcached" "Clear Memcached" "Remove Memcached")
fi
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
options=("Enable Memcached" "Restart Memcached" "Config Memcached" "Clear Memcached" "Remove Memcached")
fi
fi
#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
if [ "`systemctl is-active memcached.service`" == "active" ]; then
options=("Disable Memcached" "Restart Memcached" "Config Memcached" "Clear Memcached" "Remove Memcached")
else
options=("Enable Memcached" "Restart Memcached" "Config Memcached" "Clear Memcached" "Remove Memcached")
fi
fi
printf "=========================================================================\n"
printf "                KDATA-VPS - Quan Ly VPS/Server by KDATA.VN \n"
printf "=========================================================================\n"
printf "                            Quan Ly Memcached \n"
printf "=========================================================================\n"

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
echo "        Memcached Status: Running - Configured RAM Usage: $CACHESIZE MB"
fi
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
echo "                      Memcached Status: Stopped"
fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "`systemctl is-active memcached.service`" == "active" ]; then
echo "        Memcached Status: Running - Configured RAM Usage: $(/bin/systemctl status  memcached.service | awk 'NR==6 {print $8}') MB"
else
echo "                      Memcached Status: Stopped"
fi
fi
printf "=========================================================================\n"
printf "Link Memcached Manage: http://$serverip:$priport/memcache.php\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in

    1 ) /etc/kdata/menu/memcache/kdata-before-bat-tat-memcache;;
    2 ) /etc/kdata/menu/memcache/kdata-memcache-restart;;
    3 ) /etc/kdata/menu/memcache/kdata-memcache-change-size;;
    4 ) /etc/kdata/menu/memcache/kdata-clear-memcache;; 
    5 ) /etc/kdata/menu/memcache/kdata-install-remove-memcache;;

$(( ${#options[@]}+1 )) ) echo "";  clear && /bin/kdata;;
     *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done
