#!/bin/sh
. /home/kdata.conf
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/kdata/menu/memcache/kdata-tat-memcache
exit
fi
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
/etc/kdata/menu/memcache/kdata-bat-memcache
clear
exit
fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "`systemctl is-active memcached.service`" == "active" ]; then
clear
/etc/kdata/menu/memcache/kdata-tat-memcache
exit
fi
if [ ! "`systemctl is-active memcached.service`" == "active" ]; then
clear
/etc/kdata/menu/memcache/kdata-bat-memcache
exit
fi
fi
clear
echo "========================================================================="
echo "Sorry, KDATA-VPS khong phat hien Memcached tren he thong !"
kdata
exit
fi
